import json
from datetime import datetime
from src.utils.paths import OUTPUTS_DIR


def reschedule_by_completed_days(
    company: str,
    completed_task_ids: list,
) -> dict:
    """
    Local-only rescheduler — zero API calls, zero cost.

    What it does:
    1. Marks tasks in completed_task_ids as completed=True
    2. Any task whose date is in the past AND is not completed
       gets shifted to today with priority='high' (overdue)

    Requires the schedule to have been generated by gemini_agent.py
    which injects 'id', 'date', and 'completed' fields via
    _inject_ids_and_dates() during post-processing.

    Args:
        company            : company name (used to find the right schedule file)
        completed_task_ids : list of task id strings e.g. ['d1_t1', 'd2_t3']

    Returns:
        The updated plan dict (also saved back to disk).
    """
    slug = company.lower().replace(" ", "_").replace(".", "")
    path = OUTPUTS_DIR / f"{slug}_schedule.json"

    if not path.exists():
        raise FileNotFoundError(
            f"No schedule found for '{company}' at {path}. "
            "Generate a plan first via /generate-plan."
        )

    with open(path, "r", encoding="utf-8") as f:
        plan = json.load(f)

    today_str        = datetime.now().strftime("%Y-%m-%d")
    completed_set    = set(completed_task_ids)
    tasks_completed  = 0
    tasks_rescheduled = 0

    for block in plan.get("schedule", []):
        block_date = block.get("date", "")

        for task in block.get("tasks", []):
            task_id = task.get("id", "")

            # 1. Mark completed if in payload
            if task_id in completed_set:
                task["completed"] = True
                tasks_completed  += 1

            # 2. Reschedule overdue incomplete tasks to today
            if (
                block_date
                and block_date < today_str
                and not task.get("completed", False)
            ):
                task["date"]     = today_str
                task["priority"] = "high"
                tasks_rescheduled += 1

    # Save updated plan back to same file
    with open(path, "w", encoding="utf-8") as f:
        json.dump(plan, f, indent=4)

    print(
        f"[Rescheduler] ✅ {tasks_completed} tasks marked complete, "
        f"{tasks_rescheduled} overdue tasks shifted to {today_str}"
    )

    return plan